[project]
name = "python-packet-sniffer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "scapy>=2.7.0",
]
